version: '3.8'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: es
    environment:
      - node.name=es
      - cluster.name=es
      - discovery.seed_hosts=es
      - cluster.initial_master_nodes=es
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - serilog-with-elk-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  kib:
    image: docker.elastic.co/kibana/kibana:7.9.3
    container_name: kib
    ports:
      - 5601:5601
    environment: 
      ELASTICSEARCH_URL: http://es:9200
      ELASTICSEARCH_HOSTS: http://es:9200
    networks:
      - elastic

volumes:
  serilog-with-elk-data:
    driver: local

networks:
  elastic:
    driver: bridge